version: '3.8'

volumes:
  db_data:

services:
  db:
    image: postgres
    container_name: star-burger-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    container_name: star-burger-frontend
    command: ./node_modules/.bin/parcel watch ./bundles-src/index.js --dist-dir bundles --public-url "./"
    volumes:
      - ./bundles:/opt/frontend/bundles
      - ./bundles-src:/opt/frontend/bundles-src
    ports:
      - "1234:1234"

  backend:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.backend
    container_name: star-burger-backend
    command: bash -c "python /opt/django/manage.py migrate --noinput && python /opt/django/manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./:/opt/django
    ports:
      - "8000:8000"
    env_file:
      - ./.env
