FROM node:16

WORKDIR /frontend

COPY ./package.json /frontend
COPY ./package-lock.json /frontend
COPY ./bundles-src /frontend/bundles-src

RUN npm install --dev
RUN npm install -g parcel@2.0.0-beta.2

CMD parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
# CMD parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"