FROM --platform=linux/amd64 node:lts

WORKDIR /opt/frontend

COPY package.json /opt/frontend/package.json
COPY package-lock.json /opt/frontend/package-lock.json

RUN npm ci --dev

COPY /bundles-src /opt/frontend/bundles-src

EXPOSE 1234
