version: '3.8'

volumes:
  db_data:

services:
  db:
    image: postgres
    container_name: star-burger-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  backend:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.backend
    container_name: star-burger-backend
    command: bash -c "python /opt/django/manage.py migrate --noinput && python /opt/django/manage.py collectstatic --noinput && gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - ./:/opt/django
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    env_file:
      - ./.env

  nginx:
    depends_on:
      - backend
    build: ./nginx
    container_name: star-burger-nginx
    ports:
      - 80:80
    volumes:
      - ./static:/opt/static
      - ./media:/opt/media
    