version: '3.8'

volumes:
  db_data:

services:
  db:
    image: postgres
    container_name: star-burger-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    container_name: star-burger-frontend
    command: bash -c "parcel watch bundles-src/index.js -d bundles --public-url='./'"
    volumes:
      - ./bundles:/frontend/bundles

  backend:
    build:
      dockerfile: Dockerfile.backend
    container_name: star-burger-backend
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py collectstatic --noinput && gunicorn star_burger.wsgi:application --bind 0.0.0.0:8081"
    restart: always
    volumes:
      - ./bundles:/code/bundles
      - ./media:/code/media
      - ./:/code
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./static:/opt/static
      - ./media:/opt/media
    depends_on:
      - backend