FROM node:lts

RUN mkdir /app

WORKDIR /app

COPY package*.json ./

RUN npm ci --dev

COPY . .
EXPOSE 3000

CMD ["./node_modules/.bin/parcel", "build", "./bundles-src/index.js", "--dist-dir", "./bundles", "--public-url", "./"]