FROM --platform=linux/amd64 python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /opt/django

COPY requirements.txt /opt/django/requirements.txt

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000
