version: '3.8'

volumes:
  db_data:

services:
  db:
    image: postgres
    container_name: star-burger-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=star_burger
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ./.env

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    container_name: star-burger-frontend
    command: bash -c "parcel watch bundles-src/index.js -d bundles --public-url='./'"
    volumes:
      - ./bundles:/code/bundles

  backend:
    build:
      dockerfile: Dockerfile.backend
    container_name: star-burger-backend
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./bundles:/code/bundles
      - ./media:/code/media
      - ./:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=star_burger
    env_file:
      - ./.env
    depends_on:
      - db