# Generated by Django 3.2 on 2022-03-26 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('lat', models.FloatField(default=None, null=True, verbose_name='широта')),
                ('lon', models.FloatField(default=None, null=True, verbose_name='долгота')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата запроса')),
            ],
            options={
                'verbose_name': 'координаты',
                'verbose_name_plural': 'координаты',
            },
        ),
    ]
