# Generated by Django 3.2 on 2022-03-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordinate',
            new_name='Coordinates',
        ),
    ]
