# Generated by Django 3.2 on 2022-03-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_rename_adress_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
