# Generated by Django 3.2 on 2022-03-22 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_position_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='foodcartapp.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='position',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='foodcartapp.product', verbose_name='товар'),
        ),
    ]
