# Generated by Django 3.2 on 2022-03-23 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20220322_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость позиции'),
            preserve_default=False,
        ),
    ]
