# Generated by Django 3.2 on 2022-03-23 12:02

from django.db import migrations


def fit_position_cost(apps, schema_editor):
    Position = apps.get_model('foodcartapp', 'Position')
    positions = Position.objects.all()

    for position in positions.iterator():
        position.cost = position.quantity * position.product.price
        position.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_position_cost'),
    ]

    operations = [
        migrations.RunPython(fit_position_cost)
    ]
