# Generated by Django 3.2 on 2022-03-23 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20220323_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость позиции'),
        ),
    ]
