# Generated by Django 3.2 on 2022-03-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_position_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NW', 'новый'), ('PD', 'обработан')], db_index=True, default='NW', max_length=12, verbose_name='статус заказа'),
        ),
    ]
