# Generated by Django 3.2 on 2022-03-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20220325_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CH', 'Наличностью'), ('CD', 'Электронно')], db_index=True, default='CH', max_length=12, verbose_name='способ оплаты'),
        ),
    ]
