# Generated by Django 3.2 on 2022-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CH', 'наличные'), ('CD', 'карточкой')], db_index=True, default='CH', max_length=12, verbose_name='способ оплаты'),
        ),
    ]
