# Generated by Django 3.2 on 2022-04-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NW', 'новый'), ('PD', 'обработан'), ('BT', 'доставлен')], db_index=True, default='NW', max_length=12, verbose_name='статус заказа'),
        ),
    ]
