# Generated by Django 3.2 on 2022-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CH', 'наличные'), ('CD', 'карточкой'), ('UD', 'не указано')], db_index=True, default='UD', max_length=12, verbose_name='способ оплаты'),
        ),
    ]
